### ISSUE TITLE
Nit: id할당 방법 변경

### ISSUE THREAD

**Issue by krung2** [gimhanul/GajyeoGa#2]
https://github.com/gimhanul/GajyeoGa/blob/7b78f15e8e31847bee55099d40a2023b08301660/app/templates/test.html#L36-L38

javascript ES6부터 생긴 `object-shorthand`를 이용하여

```javascript
const data = { 
     id,
 } 
```
로 대체할 수 있습니다

**Comment by gimhanul** [comment]
와 대박!!!
